In [1]:
import numpy as np
data = np.loadtxt("0000000000002419_training_ccpp_x_y_train.csv", delimiter = ",")

In [2]:
data

array([[    8.58,    38.38,  1021.03,    84.37,   482.26],
       [   21.79,    58.2 ,  1017.21,    66.74,   446.94],
       [   16.64,    48.92,  1011.55,    78.76,   452.56],
       ..., 
       [   29.8 ,    69.34,  1009.36,    64.74,   437.65],
       [   16.37,    54.3 ,  1017.94,    63.63,   459.97],
       [   30.11,    62.04,  1010.69,    47.96,   444.42]])

In [3]:
data.shape

(7176, 5)

In [4]:
data[0,:]

array([    8.58,    38.38,  1021.03,    84.37,   482.26])

In [5]:
x1 = data[:, 0:4]
x1

array([[    8.58,    38.38,  1021.03,    84.37],
       [   21.79,    58.2 ,  1017.21,    66.74],
       [   16.64,    48.92,  1011.55,    78.76],
       ..., 
       [   29.8 ,    69.34,  1009.36,    64.74],
       [   16.37,    54.3 ,  1017.94,    63.63],
       [   30.11,    62.04,  1010.69,    47.96]])

In [6]:
y = data[:, 4]
y.shape

(7176,)

In [7]:
x = np.zeros((7176, 5))
x[:, :-1] = x1
x[:, -1] = 1

In [8]:
x.shape

(7176, 5)

In [9]:
import pandas as pd
df = pd.DataFrame(x)
df.describe()

0            1            2            3       4
count  7176.000000  7176.000000  7176.000000  7176.000000  7176.0
mean     19.629712    54.288154  1013.263032    73.275818     1.0
std       7.475256    12.751468     5.964863    14.625093     0.0
min       1.810000    25.360000   992.890000    25.560000     1.0
25%      13.470000    41.740000  1009.010000    63.202500     1.0
50%      20.315000    52.050000  1012.910000    74.895000     1.0
75%      25.720000    66.540000  1017.302500    84.925000     1.0
max      35.770000    81.560000  1033.300000   100.160000     1.0

In [10]:
m = np.zeros((5))
m

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
m.shape

(5,)

In [12]:
def step_gradient(x,y,learning_rate, m):
    m_slope = np.zeros((5))
    num_rows = 7176
    for i in range(num_rows):
        x_rowwise = x[i, :]   #1 d np array with x values of ith row
        y_rowwise = y[i]   # y value for ith row
        m_slope += (-2/7176)*(y_rowwise - (m*x_rowwise).sum())*x_rowwise
    new_m  = np.zeros((5))
    new_m = m - learning_rate * m_slope
    return new_m

In [13]:
def cost(x,y,m):
    total_cost = 0
    for i in range(7176): #for each row
        x_rowwise = x[i] #1 d np array with x values of ith row
        y_rowwise = y[i] # y value for ith row
        new = x_rowwise*m # new is an array obtained by element by element multiplication of x_rowwise and m
        mx_sum = 0 
        for j in range(len(new)): #to calculate sum of elements of new
            mx_sum += new[j]
        total_cost += (1/7176)*((y_rowwise - mx_sum)**2)
    return total_cost

In [14]:
def gd(x,y,learning_rate, num_iterations,m):
    for i in range(num_iterations):
        m = step_gradient(x,y,learning_rate,m)
        if(i%1000==99):
            print(i, "cost:", cost(x,y,m))
    return m

In [15]:
def run():
    learning_rate = 0.0000001
    num_iterations = 150000
    m = np.zeros((5))
    m = gd(x,y, learning_rate, num_iterations,m)
    print (m)
    return (m)

In [16]:
m = run()

99 cost: 255.672083638
1099 cost: 235.847120215
2099 cost: 218.007712495
3099 cost: 201.945751901
4099 cost: 187.475439179
5099 cost: 174.4308656
6099 cost: 162.66385788
7099 cost: 152.042057982
8099 cost: 142.447212121
9099 cost: 133.773646125
10099 cost: 125.926906766
11099 cost: 118.822550954
12099 cost: 112.385066631
13099 cost: 106.546910979
14099 cost: 101.247653156
15099 cost: 96.433210117
16099 cost: 92.0551654031
17099 cost: 88.0701618113
18099 cost: 84.4393599123
19099 cost: 81.1279552276
20099 cost: 78.1047476737
21099 cost: 75.3417575814
22099 cost: 72.8138832161
23099 cost: 70.4985952822
24099 cost: 68.375664387
25099 cost: 66.4269178798
26099 cost: 64.6360228711
27099 cost: 62.9882925904
28099 cost: 61.4705135444
29099 cost: 60.0707912209
30099 cost: 58.7784123256
31099 cost: 57.5837217599
32099 cost: 56.4780127428
33099 cost: 55.4534286543
34099 cost: 54.5028753327
35099 cost: 53.6199426959
36099 cost: 52.7988346797
37099 cost: 52.0343065966
38099 cost: 51.3216091149
390

In [20]:
m

array([ -7.19671252e-01,  -7.12019952e-01,   4.96516182e-01,
         5.60416716e-02,   3.89638262e-04])

In [21]:
test_data = np.loadtxt("0000000000002419_test_ccpp_x_test.csv", delimiter = ",")
test_data.shape

(2392, 4)

In [23]:
x_test = np.zeros((2392, 5))
x_test[:, :-1] = test_data
x_test[:, -1] = 1

In [24]:
x_test.shape

(2392, 5)

In [25]:
test_df = pd.DataFrame(x_test)
test_df.describe()

0            1            2            3       4
count  2392.00000  2392.000000  2392.000000  2392.000000  2392.0
mean     19.71579    54.358754  1013.247216    73.408457     1.0
std       7.38488    12.578763     5.861068    14.528135     0.0
min       3.38000    25.360000   993.740000    26.670000     1.0
25%      13.66000    41.730000  1009.300000    63.615000     1.0
50%      20.45000    52.750000  1013.025000    75.090000     1.0
75%      25.67250    66.490000  1017.172500    84.497500     1.0
max      37.11000    80.250000  1033.290000   100.130000     1.0

In [26]:
y2 = np.zeros((2392))
for i in range(2392):
    x2 = x_test[i, :]
    sum = 0
    for j in range(5):
        sum = sum + m[j] * x_test[i][j]
    y2[i] = sum

In [27]:
y2

array([ 471.81268372,  471.4625995 ,  430.98236464, ...,  441.50584638,
        459.72848756,  452.12393419])

In [28]:
np.savetxt("pred1.csv",y2)